apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- helmreleases/chaoskube.yaml
- namespaces/kube-system/namespace.yaml
- namespaces/platform-system/namespace.yaml
- namespaces/sealed-secrets/namespace.yaml
- sealed-secrets/crd.yaml
- sealed-secrets/helmrelease.yaml
- storageclasses/general-purpose-delete.yaml
- storageclasses/general-purpose-retain.yaml